In [1]:
import datatable as dt
from datatable import join, by, f, min, max, mean, sd
import pandas as pd
from itertools import permutations, combinations
from random import sample

In [2]:
X = dt.fread("churn_test.csv")
XP = X.to_pandas()

In [3]:
X

,customer_id,is_churn,city,age,gender,registration_method,registration_date,plan_list_price,avg_amount_paid,auto_renew,times_under_paid,num_transactions,num_payment_methods,common_payment_method
,▪▪▪▪,▪,▪▪▪▪,▪▪▪▪,▪▪▪▪,▪▪▪▪,▪▪▪▪,▪▪▪▪▪▪▪▪,▪▪▪▪▪▪▪▪,▪▪▪▪,▪▪▪▪,▪▪▪▪,▪▪▪▪,▪▪▪▪
0,NE/UaeYRIg/N7zXd3aXsUWteq0qBfdlm5vkcbAoqRII=,0,15,35,female,3,2012-09-15,143.481,149,YES,0,27,2,37
1,iaFOZLU0qbwsK0ZMzShbZw9LChI/AGXuEXGnM7+dw9U=,0,13,31,male,7,2011-08-04,156.316,164.158,NO,0,19,2,36
2,GO/h+rwlZOY9qo9HuDbEe8a9JUQlhXwcMX8SfSmUoTM=,0,1,NA,,7,2015-12-19,99,99,YES,0,15,1,41
3,2Mnslz6gf20bvmfDDU1ZRMcdzpAIA5r6MaN6VxdRKGY=,0,1,NA,,7,2013-10-09,115.704,121.222,YES,0,27,1,41
4,VogQh7sS6ffvuqzchH+s5layvdwA8pW76KHphLkCaXk=,0,1,NA,,7,2015-09-02,99,99,YES,0,18,1,41
5,yiJwVUkVSt0YnPR50vpr3gAAiBj9OzEz3yjJ2OcDPv0=,0,1,NA,,7,2015-09-17,119,59.4,YES,2,5,1,41
6,PgR6murfNXGb/OixcY4bjBh4sxdn2SDsc3dfqaBwVLw=,1,13,34,female,9,2011-08-15,1599,1599,NO,0,1,1,32
7,DIM22nfDWMDFPK3etbFMjhx0avdOPSkrKG4vsbGzEqo=,0,1,NA,,7,2014-01-22,149,149,YES,0,26,1,41
8,HHPXAZ+WZLGy55n2iGqNRfmYNgfMGxqTZ5rP3XOsSKY=,0,13,32,male,9,2007-11-09,110.13,149,YES,0,23,1,34
9,Ts49FE9BCCM4aBeNKo0K3lsIP/kwR20+fYRcjOKPYCU=,0,1,NA,,7,2013-03-17,110.765,110.765,YES,0,17,1,41
⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮,⋮
9995,4Z9M2J7/VWoydHQRHaKD8EB9kmxRyK/xnR+ZJHTxmC4=,0,1,NA,,7,2014-01-08,143.269,149,YES,0,26,1,41
9996,r2zEXxxVPrrwLM/x0vZtcXQS14dL0s+N/TlVnprubX4=,0,1,NA,,4,2016-10-23,149,149,NO,0,4,1,38
9997,BYHixvOh4JOZrRNKkokya1gvhBsq9p5agWhgfzJzN+U=,0,1,NA,,7,2016-12-20,99,99,YES,0,3,1,41
9998,Em2vd4Ewgv/t4T9xKb2VgG1Ta9JYJWwKw2SXLqzhNy4=,0,1,NA,,7,2012-04-06,135.107,140.429,YES,0,28,1,41
9999,mkZMUi61IfT2o5HT+/g1zcbaNYIn7kNcLyiK7oQWJJc=,0,1,NA,,7,2015-09-02,99,99,YES,0,18,1,41

In [4]:
uniques = X.nunique().to_list()
nrows = X.nrows
ncols = X.ncols

In [5]:
X_num = X[:, [float, int]]
X_cat = X[:, [str]]

In [6]:
X_cat

,customer_id,gender,registration_date,auto_renew
,▪▪▪▪,▪▪▪▪,▪▪▪▪,▪▪▪▪
0,NE/UaeYRIg/N7zXd3aXsUWteq0qBfdlm5vkcbAoqRII=,female,2012-09-15,YES
1,iaFOZLU0qbwsK0ZMzShbZw9LChI/AGXuEXGnM7+dw9U=,male,2011-08-04,NO
2,GO/h+rwlZOY9qo9HuDbEe8a9JUQlhXwcMX8SfSmUoTM=,,2015-12-19,YES
3,2Mnslz6gf20bvmfDDU1ZRMcdzpAIA5r6MaN6VxdRKGY=,,2013-10-09,YES
4,VogQh7sS6ffvuqzchH+s5layvdwA8pW76KHphLkCaXk=,,2015-09-02,YES
5,yiJwVUkVSt0YnPR50vpr3gAAiBj9OzEz3yjJ2OcDPv0=,,2015-09-17,YES
6,PgR6murfNXGb/OixcY4bjBh4sxdn2SDsc3dfqaBwVLw=,female,2011-08-15,NO
7,DIM22nfDWMDFPK3etbFMjhx0avdOPSkrKG4vsbGzEqo=,,2014-01-22,YES
8,HHPXAZ+WZLGy55n2iGqNRfmYNgfMGxqTZ5rP3XOsSKY=,male,2007-11-09,YES
9,Ts49FE9BCCM4aBeNKo0K3lsIP/kwR20+fYRcjOKPYCU=,,2013-03-17,YES
⋮,⋮,⋮,⋮,⋮
9995,4Z9M2J7/VWoydHQRHaKD8EB9kmxRyK/xnR+ZJHTxmC4=,,2014-01-08,YES
9996,r2zEXxxVPrrwLM/x0vZtcXQS14dL0s+N/TlVnprubX4=,,2016-10-23,NO
9997,BYHixvOh4JOZrRNKkokya1gvhBsq9p5agWhgfzJzN+U=,,2016-12-20,YES
9998,Em2vd4Ewgv/t4T9xKb2VgG1Ta9JYJWwKw2SXLqzhNy4=,,2012-04-06,YES
9999,mkZMUi61IfT2o5HT+/g1zcbaNYIn7kNcLyiK7oQWJJc=,,2015-09-02,YES

In [7]:
X_num
type(X_num.names)

tuple

In [8]:
strlist = []
[strlist.append(s) for s in X_cat.names]

strlist.remove("customer_id")
intlist = []
[intlist.append(i) for i in X_num.names]
    
print(strlist)
print(intlist)
agglist = ['mean','max']

['gender', 'registration_date', 'auto_renew']
['plan_list_price', 'avg_amount_paid', 'city', 'age', 'registration_method', 'times_under_paid', 'num_transactions', 'num_payment_methods', 'common_payment_method']

In [9]:
# Generate combination grouping
# gglist at the end has single col + combinations of multiple cat columns
#
max_len_groups = 4 # Maximum of 4 col group bys
gglist = []

# Include all individual cols by default
[gglist.append(j) for j in strlist]

# Create combinations (ordered permutations)
# Assumption, cat column order is somewhat hiearchical 
tmp_gg_list = []
for j in range(1, max_len_groups):
    comb = combinations(strlist,j+1) 
    comb_list = list(comb)
    for r in comb_list:
        if (len(r) <= max_len_groups):
            tmp_gg_list.append(r) 
            
[gglist.append(x) for x in tmp_gg_list]

[None, None, None, None]

In [10]:
gglist

['gender',
 'registration_date',
 'auto_renew',
 ('gender', 'registration_date'),
 ('gender', 'auto_renew'),
 ('registration_date', 'auto_renew'),
 ('gender', 'registration_date', 'auto_renew')]

In [11]:
len(gglist)*len(intlist)*len(agglist)

126

In [12]:
groups = 0

for i in gglist: # Walk through Group By cols, 1 Combination at a time
    y = []
    # y - holds the BY clause for data table GROUP BY
    # agg_y_colname - holds Column name to go into data table. Otherwise default will be C0
    if (isinstance(i,tuple)):
        y = ','.join("dt.f."+g for g in i)     
        agg_y_colname = '_'.join(g for g in i)
    else:
        y = "dt.f."+i
        agg_y_colname = i  

    for j in range(0,len(intlist)): # Walk through Numeric cols 1 by 1
        x = intlist[j]
        for z in range(0,len(agglist)): # Walk through Aggregates 1 by 1
            agg = agglist[z]
            # Final column name a mix of GROUP BY column name, Numeric Column and Aggregator
            agg_colname = "GroupBy_"+agg_y_colname.upper()+"_"+agg+"_of_"+x.upper()
            # FINAL DATA TABLE GROUP BY CLAUSE
            group_by = "X[:, dt."+agg+"(dt.f."+x+"),by("+y+")]"
            groups +=1
            F = eval(group_by) # DATA TABLE GROUP BY EXECUTION
            F.names = {'C0':agg_colname}
            print(str(groups)+":  "+agg_colname)
            c = F[:,1].countna()
            # Add to features only if there are no NAs in the cols
            if (c[0,0] == 0):  
                FP = F.to_pandas()
                XP = pd.merge(XP, FP, how='inner')

1:  GroupBy_GENDER_mean_of_PLAN_LIST_PRICE
2:  GroupBy_GENDER_max_of_PLAN_LIST_PRICE
3:  GroupBy_GENDER_mean_of_AVG_AMOUNT_PAID
4:  GroupBy_GENDER_max_of_AVG_AMOUNT_PAID
5:  GroupBy_GENDER_mean_of_CITY
6:  GroupBy_GENDER_max_of_CITY
7:  GroupBy_GENDER_mean_of_AGE
8:  GroupBy_GENDER_max_of_AGE
9:  GroupBy_GENDER_mean_of_REGISTRATION_METHOD
10:  GroupBy_GENDER_max_of_REGISTRATION_METHOD
11:  GroupBy_GENDER_mean_of_TIMES_UNDER_PAID
12:  GroupBy_GENDER_max_of_TIMES_UNDER_PAID
13:  GroupBy_GENDER_mean_of_NUM_TRANSACTIONS
14:  GroupBy_GENDER_max_of_NUM_TRANSACTIONS
15:  GroupBy_GENDER_mean_of_NUM_PAYMENT_METHODS
16:  GroupBy_GENDER_max_of_NUM_PAYMENT_METHODS
17:  GroupBy_GENDER_mean_of_COMMON_PAYMENT_METHOD
18:  GroupBy_GENDER_max_of_COMMON_PAYMENT_METHOD
19:  GroupBy_REGISTRATION_DATE_mean_of_PLAN_LIST_PRICE
20:  GroupBy_REGISTRATION_DATE_max_of_PLAN_LIST_PRICE
21:  GroupBy_REGISTRATION_DATE_mean_of_AVG_AMOUNT_PAID
22:  GroupBy_REGISTRATION_DATE_max_of_AVG_AMOUNT_PAID
23:  GroupBy_REGISTRATION_DATE_mean_of_CITY
24:  GroupBy_REGISTRATION_DATE_max_of_CITY
25:  GroupBy_REGISTRATION_DATE_mean_of_AGE
26:  GroupBy_REGISTRATION_DATE_max_of_AGE
27:  GroupBy_REGISTRATION_DATE_mean_of_REGISTRATION_METHOD
28:  GroupBy_REGISTRATION_DATE_max_of_REGISTRATION_METHOD
29:  GroupBy_REGISTRATION_DATE_mean_of_TIMES_UNDER_PAID
30:  GroupBy_REGISTRATION_DATE_max_of_TIMES_UNDER_PAID
31:  GroupBy_REGISTRATION_DATE_mean_of_NUM_TRANSACTIONS
32:  GroupBy_REGISTRATION_DATE_max_of_NUM_TRANSACTIONS
33:  GroupBy_REGISTRATION_DATE_mean_of_NUM_PAYMENT_METHODS
34:  GroupBy_REGISTRATION_DATE_max_of_NUM_PAYMENT_METHODS
35:  GroupBy_REGISTRATION_DATE_mean_of_COMMON_PAYMENT_METHOD
36:  GroupBy_REGISTRATION_DATE_max_of_COMMON_PAYMENT_METHOD
37:  GroupBy_AUTO_RENEW_mean_of_PLAN_LIST_PRICE
38:  GroupBy_AUTO_RENEW_max_of_PLAN_LIST_PRICE
39:  GroupBy_AUTO_RENEW_mean_of_AVG_AMOUNT_PAID
40:  GroupBy_AUTO_RENEW_max_of_AVG_AMOUNT_PAID
41:  GroupBy_AUTO_RENEW_mean_of_CITY
42:  GroupBy_AUTO_RENEW_max_of_CITY
43:  GroupBy_AUTO_RENEW_mean_of_AGE
44:  GroupBy_AUTO_RENEW_max_of_AGE
45:  GroupBy_AUTO_RENEW_mean_of_REGISTRATION_METHOD
46:  GroupBy_AUTO_RENEW_max_of_REGISTRATION_METHOD
47:  GroupBy_AUTO_RENEW_mean_of_TIMES_UNDER_PAID
48:  GroupBy_AUTO_RENEW_max_of_TIMES_UNDER_PAID
49:  GroupBy_AUTO_RENEW_mean_of_NUM_TRANSACTIONS
50:  GroupBy_AUTO_RENEW_max_of_NUM_TRANSACTIONS
51:  GroupBy_AUTO_RENEW_mean_of_NUM_PAYMENT_METHODS
52:  GroupBy_AUTO_RENEW_max_of_NUM_PAYMENT_METHODS
53:  GroupBy_AUTO_RENEW_mean_of_COMMON_PAYMENT_METHOD
54:  GroupBy_AUTO_RENEW_max_of_COMMON_PAYMENT_METHOD
55:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_PLAN_LIST_PRICE
56:  GroupBy_GENDER_REGISTRATION_DATE_max_of_PLAN_LIST_PRICE
57:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_AVG_AMOUNT_PAID
58:  GroupBy_GENDER_REGISTRATION_DATE_max_of_AVG_AMOUNT_PAID
59:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_CITY
60:  GroupBy_GENDER_REGISTRATION_DATE_max_of_CITY
61:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_AGE
62:  GroupBy_GENDER_REGISTRATION_DATE_max_of_AGE
63:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_REGISTRATION_METHOD
64:  GroupBy_GENDER_REGISTRATION_DATE_max_of_REGISTRATION_METHOD
65:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_TIMES_UNDER_PAID
66:  GroupBy_GENDER_REGISTRATION_DATE_max_of_TIMES_UNDER_PAID
67:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_NUM_TRANSACTIONS
68:  GroupBy_GENDER_REGISTRATION_DATE_max_of_NUM_TRANSACTIONS
69:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_NUM_PAYMENT_METHODS
70:  GroupBy_GENDER_REGISTRATION_DATE_max_of_NUM_PAYMENT_METHODS
71:  GroupBy_GENDER_REGISTRATION_DATE_mean_of_COMMON_PAYMENT_METHOD
72:  GroupBy_GENDER_REGISTRATION_DATE_max_of_COMMON_PAYMENT_METHOD
73:  GroupBy_GENDER_AUTO_RENEW_mean_of_PLAN_LIST_PRICE
74:  GroupBy_GENDER_AUTO_RENEW_max_of_PLAN_LIST_PRICE
75:  GroupBy_GENDER_AUTO_RENEW_mean_of_AVG_AMOUNT_PAID
76:  GroupBy_GENDER_AUTO_RENEW_max_of_AVG_AMOUNT_PAID
77:  GroupBy_GENDER_AUTO_RENEW_mean_of_CITY
78:  GroupBy_GENDER_AUTO_RENEW_max_of_CITY
79:  GroupBy_GENDER_AUTO_RENEW_mean_of_AGE
80:  GroupBy_GENDER_AUTO_RENEW_max_of_AGE
81:  GroupBy_GENDER_AUTO_RENEW_mean_of_REGISTRATION_METHOD
82:  GroupBy_GENDER_AUTO_RENEW_max_of_REGISTRATION_METHOD
83:  GroupBy_GENDER_AUTO_RENEW_mean_of_TIMES_UNDER_PAID
84:  GroupBy_GENDER_AUTO_RENEW_max_of_TIMES_UNDER_PAID
85:  GroupBy_GENDER_AUTO_RENEW_mean_of_NUM_TRANSACTIONS
86:  GroupBy_GENDER_AUTO_RENEW_max_of_NUM_TRANSACTIONS
87:  GroupBy_GENDER_AUTO_RENEW_mean_of_NUM_PAYMENT_METHODS
88:  GroupBy_GENDER_AUTO_RENEW_max_of_NUM_PAYMENT_METHODS
89:  GroupBy_GENDER_AUTO_RENEW_mean_of_COMMON_PAYMENT_METHOD
90:  GroupBy_GENDER_AUTO_RENEW_max_of_COMMON_PAYMENT_METHOD
91:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_PLAN_LIST_PRICE
92:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_PLAN_LIST_PRICE
93:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_AVG_AMOUNT_PAID
94:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_AVG_AMOUNT_PAID
95:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_CITY
96:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_CITY
97:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_AGE
98:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_AGE
99:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_REGISTRATION_METHOD
100:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_REGISTRATION_METHOD
101:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_TIMES_UNDER_PAID
102:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_TIMES_UNDER_PAID
103:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_TRANSACTIONS
104:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_TRANSACTIONS
105:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_PAYMENT_METHODS
106:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_PAYMENT_METHODS
107:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_mean_of_COMMON_PAYMENT_METHOD
108:  GroupBy_REGISTRATION_DATE_AUTO_RENEW_max_of_COMMON_PAYMENT_METHOD
109:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_PLAN_LIST_PRICE
110:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_PLAN_LIST_PRICE
111:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_AVG_AMOUNT_PAID
112:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_AVG_AMOUNT_PAID
113:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_CITY
114:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_CITY
115:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_AGE
116:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_AGE
117:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_REGISTRATION_METHOD
118:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_REGISTRATION_METHOD
119:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_TIMES_UNDER_PAID
120:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_TIMES_UNDER_PAID
121:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_TRANSACTIONS
122:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_TRANSACTIONS
123:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_PAYMENT_METHODS
124:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_PAYMENT_METHODS
125:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_COMMON_PAYMENT_METHOD
126:  GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_COMMON_PAYMENT_METHOD

In [13]:
XP

,customer_id,is_churn,city,age,gender,registration_method,registration_date,plan_list_price,avg_amount_paid,auto_renew,...,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_REGISTRATION_METHOD,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_REGISTRATION_METHOD,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_TIMES_UNDER_PAID,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_TIMES_UNDER_PAID,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_TRANSACTIONS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_TRANSACTIONS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_PAYMENT_METHODS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_PAYMENT_METHODS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_COMMON_PAYMENT_METHOD,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_COMMON_PAYMENT_METHOD
0,NE/UaeYRIg/N7zXd3aXsUWteq0qBfdlm5vkcbAoqRII=,0,15,35.0,female,3,2012-09-15,143.481481,149.000000,YES,...,3.000000,3,0.000000,0,27.000000,27,2.000000,2,37.000000,37
1,AHoM4pZ2BLfMbnRj0Vrqsc/ENUIZje2WyMH0M9fytHs=,0,6,27.0,male,7,2012-09-15,149.000000,149.000000,YES,...,8.000000,9,0.000000,0,24.500000,26,2.000000,3,39.500000,41
2,qRV18svd05eDrT1K3W/aeulaB2kvWXrwwvu12kTmSgI=,1,5,23.0,male,9,2012-09-15,136.043478,149.000000,YES,...,8.000000,9,0.000000,0,24.500000,26,2.000000,3,39.500000,41
3,rhywmIelJyYFpgkdC/tuXSQjd9x1Y4rZGvq/hHDpRAo=,0,6,NaN,,7,2012-09-15,141.157895,149.000000,YES,...,7.000000,7,0.000000,0,19.000000,19,1.000000,1,39.000000,39
4,7INLvIFXyHL413MkmJMbRyZRTJSRUpQqXE/Ky8rRuoo=,0,5,29.0,female,9,2015-01-15,149.000000,143.481481,YES,...,7.000000,9,0.750000,2,25.250000,27,1.250000,2,40.250000,41
5,nb7KHok7Qh58AL/2aZo3tVvF7jvjfQZv279h+7RqHRM=,0,1,NaN,female,7,2015-01-15,149.000000,149.000000,YES,...,7.000000,9,0.750000,2,25.250000,27,1.250000,2,40.250000,41
6,JSN3lGVTBGaSClTgUlrFSr+7Sn//OBZbC0Lsp4QzQck=,0,17,25.0,female,9,2015-01-15,149.000000,149.000000,YES,...,7.000000,9,0.750000,2,25.250000,27,1.250000,2,40.250000,41
7,sW68usSOoh9pZD16M2eyCDsZykZi7+cynqTljHl0ZCg=,1,22,24.0,female,3,2015-01-15,176.090909,169.318182,YES,...,7.000000,9,0.750000,2,25.250000,27,1.250000,2,40.250000,41
8,as0DVQJ3ck1oLW7I/CUYWvNYKNL+mBNUenxuEPgxYWw=,0,4,-43.0,,9,2015-01-15,149.000000,143.269231,YES,...,8.333333,9,0.333333,1,26.333333,29,1.666667,2,36.666667,40
9,ZJWMSWlnvpmVJcCKNI24bxn10So6bgKZbfV4+rpA9ck=,1,1,NaN,,9,2015-01-15,156.125000,162.375000,YES,...,8.333333,9,0.333333,1,26.333333,29,1.666667,2,36.666667,40
10,4q/md3Le4C1szbaUyAnjA5wKC5LKqrFjaSHOhlJWTLM=,0,5,NaN,,7,2015-01-15,133.586207,149.000000,YES,...,8.333333,9,0.333333,1,26.333333,29,1.666667,2,36.666667,40
11,TSSAjQjWI8JiPmUEl193VOZZf6IBjcE1XOtObuZM1MA=,0,14,17.0,female,7,2015-11-29,139.000000,139.000000,YES,...,7.000000,7,0.000000,0,15.000000,15,1.000000,1,41.000000,41
12,+c6yigU4HJs0ugrVs9YXqQcq/p8sZZX7yKlLW7J4kws=,0,15,22.0,male,4,2015-11-29,149.000000,149.000000,YES,...,4.000000,4,0.000000,0,8.000000,8,1.000000,1,39.000000,39
13,m7RIgqtslkj12a59sQDJJXF9gAlf9JEuTTeXzvs/T14=,0,1,NaN,,7,2015-11-29,99.000000,99.000000,YES,...,7.000000,7,1.000000,2,14.500000,15,1.500000,2,38.500000,41
14,XwN4/jPSI3W3VTT2b9u1j6BskcvdkEzSCyrow+1oafI=,0,1,NaN,,7,2015-11-29,171.866667,152.000000,YES,...,7.000000,7,1.000000,2,14.500000,15,1.500000,2,38.500000,41
15,263/cds1/CIMORXzeHlAtiNIRXz+l5yLXqtdkmVMoIo=,0,13,27.0,female,3,2013-01-07,143.269231,149.000000,YES,...,4.600000,7,0.000000,0,21.200000,26,1.400000,2,36.800000,41
16,Ls1RkeKcVv5fRXUbiZDJPvWj2M1GZk/yeQMvAjRNwp4=,0,5,33.0,female,3,2013-01-07,106.428571,149.000000,YES,...,4.600000,7,0.000000,0,21.200000,26,1.400000,2,36.800000,41
17,GY8vUVm8S484ne2a7gREd8O8FpH1f52AMCsMKohbmnQ=,0,15,29.0,female,3,2013-01-07,143.269231,149.000000,YES,...,4.600000,7,0.000000,0,21.200000,26,1.400000,2,36.800000,41
18,UsMLy3LOV58HetjNHj0ql5MLI0g7U4UGolX0uoq//OA=,0,22,31.0,female,7,2013-01-07,370.142857,370.142857,YES,...,4.600000,7,0.000000,0,21.200000,26,1.400000,2,36.800000,41
19,dhkCPvqdSYLzmgxRwG+HrvoyMvxK6ZDEbIZ22cUeJaE=,0,15,23.0,female,7,2013-01-07,143.269231,149.000000,YES,...,4.600000,7,0.000000,0,21.200000,26,1.400000,2,36.800000,41
20,2D/axAm6FC52d99FYyB1woIEqYhODz/ekVG5rqMbs80=,0,13,32.0,male,3,2013-01-07,248.642857,238.000000,YES,...,3.000000,3,1.000000,1,14.000000,14,3.000000,3,40.000000,40
21,avAPtbBcu1XeNuI9G6BZxyXqesWploWlJuxKZ6RVDC8=,0,1,NaN,,7,2013-01-07,99.000000,99.000000,YES,...,6.000000,7,1.250000,5,21.000000,28,1.000000,1,40.750000,41
22,MP59gGmWL+c7j3ljAqXr7AZzIEcmegt36Np1OszwzmI=,0,1,NaN,,7,2013-01-07,99.000000,99.000000,YES,...,6.000000,7,1.250000,5,21.000000,28,1.000000,1,40.750000,41
23,ZiE5OOG81MPhranbUkiKPlO6ZiGFnDF8Nzao52Kn1GQ=,0,1,NaN,,7,2013-01-07,121.142857,115.785714,YES,...,6.000000,7,1.250000,5,21.000000,28,1.000000,1,40.750000,41
24,Hb68Pkw2n81B/NseqmUsJ7GMeWKsVNFfeyImbrd0lh4=,0,13,NaN,,3,2013-01-07,143.269231,149.000000,YES,...,6.000000,7,1.250000,5,21.000000,28,1.000000,1,40.750000,41
25,QUHrkWkYtJv176lkmYmVCRN+mU0XwdbGxK4p7fXYB+o=,0,13,24.0,female,3,2012-05-11,141.157895,149.000000,YES,...,6.000000,9,0.000000,0,22.500000,26,1.000000,1,39.500000,40
26,HSuWkTV/rjqwnak6E4bHFY8e3PUzWQxF2k4gohPrbhQ=,0,4,32.0,female,9,2012-05-11,143.269231,149.000000,YES,...,6.000000,9,0.000000,0,22.500000,26,1.000000,1,39.500000,40
27,6XgfmaqbLXyfg2cibNJvalg3ClmHtTEb2WTJZ2z3u8Q=,0,14,27.0,female,7,2013-09-03,113.851852,119.370370,YES,...,5.000000,7,0.000000,0,23.000000,27,1.000000,1,40.000000,41
28,KD0dUfZZCvoDYyq9F81J+hZA/7vkHUCSqU4Tp/UOL+8=,0,5,27.0,female,3,2013-09-03,141.157895,149.000000,YES,...,5.000000,7,0.000000,0,23.000000,27,1.000000,1,40.000000,41
29,bSQdIVUtH+80CW2xe+b4qGifJ/ggcu54Iesk2X8roiI=,0,13,NaN,female,9,2016-06-11,170.285714,170.285714,YES,...,8.333333,9,0.333333,1,8.333333,9,1.333333,2,40.333333,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,+GfZOnaUG6C2TdUv8eEAxLHkrhO1qYywsR3tBEHuIrI=,1,6,24.0,male,3,2014-02-08,164.500000,164.500000,NO,...,3.000000,3,0.000000,0,4.000000,4,2.000000,2,36.000000,36
9971,m5jkvVar+5xsxcj3pijPr5I6umqO/w8sHbvPfFjl7MU=,0,13,20.0,male,9,2015-05-31,966.000000,966.000000,NO,...,9.000000,9,0.000000,0,3.000000,3,3.000000,3,20.000000,20
9972,yRT/XhwxWnx8x8YtZNolKvoMUpA9jLEDazHFYrwFp78=,0,11,20.0,male,3,2013-03-30,180.000000,180.000000,NO,...,3.000000,3,0.000000,0,5.000000,5,1.000000,1,29.000000,29
9973,v8boh8RHM+4Ks5T7HnTysT5JeF2JrAefKGFrSyfSiB8=,1,8,30.0,male,3,2012-10-20,596.000000,894.000000,NO,...,3.000000,3,0.000000,0,3.000000,3,1.000000,1,32.000000,32
9974,kp+xHJodAPSMA9NYh79qLuFXngNkutUx4tp6N91UBH8=,0,10,34.0,male,9,2004-04-11,180.000000,180.000000,NO,...,9.000000,9,0.000000,0,2.000000,2,1.000000,1,36.000000,36
9975,bJ+fWUFLYH1Q0PSp2bxHY5k40pBr+7w9naq+B6kRbDw=,0,14,24.0,male,9,2011-07-15,140.722222,149.000000,NO,...,9.000000,9,0.000000,0,18.000000,18,1.000000,1,38.000000,38
9976,CCqd55nhBtOydyvOIdHqIrmncax8r4XM5bB5kKER0YY=,0,15,31.0,male,9,2007-12-28,894.000000,894.000000,NO,...,9.000000,9,0.000000,0,3.000000,3,1.000000,1,3.000000,3
9977,VD2IHE5pR6EVRkGYFgTX1LcpUuijD+DQxEavSBPXLXM=,0,22,20.0,male,9,2015-09-02,149.000000,149.000000,NO,...,9.000000,9,0.000000,0,18.000000,18,1.000000,1,38.000000,38
9978,0b50Ghzx8gKnrl+5/3mrGxjfBt1GS75lksJCesGedwo=,0,5,19.0,male,3,2014-09-26,144.000000,144.000000,NO,...,3.000000,3,0.000000,0,5.000000,5,2.000000,2,29.000000,29
9979,aQzg6yfJYw5AZY8qTU+F8vHrlJoP1P0GFmya9NacXdc=,0,4,18.0,male,9,2015-10-28,149.000000,149.000000,NO,...,9.000000,9,0.000000,0,14.000000,14,1.000000,1,38.000000,38
9980,zliCe5ZE1y2JSOafPvQZOSIlaKXwxvnbRIUQlzQW3p4=,1,14,33.0,male,9,2010-09-14,1788.000000,1788.000000,NO,...,9.000000,9,0.000000,0,1.000000,1,1.000000,1,32.000000,32
9981,nC+uCHzisuy31Ig5F9iuqR/bmq0njTp/J08qMXPHr2s=,0,13,25.0,male,9,2014-09-01,202.000000,202.000000,NO,...,9.000000,9,0.000000,0,20.000000,20,2.000000,2,36.000000,36
9982,oNDf1+b5Ox4qY018W/mKa3ReAXHuDDUNWABZW5IlkdQ=,0,6,18.0,male,3,2014-11-23,164.619048,164.619048,NO,...,3.000000,3,0.000000,0,21.000000,21,1.000000,1,38.000000,38
9983,6dSaRiLeSyvwOhQsIkVBm+TlX+RwhTQgvfeBsUVmUBg=,0,4,19.0,male,3,2013-07-02,894.000000,894.000000,NO,...,3.000000,3,0.000000,0,3.000000,3,1.000000,1,22.000000,22
9984,T5mcFg5oakESfi0fs5Q/i5pDGpG78STzSfVr9bhToXk=,0,14,24.0,male,3,2015-06-17,166.857143,166.857143,NO,...,3.000000,3,0.000000,0,14.000000,14,2.000000,2,36.000000,36
9985,/XHCe7seNOaEeQSRfeH/vUXEAidpxR78alL+cxmSEqE=,1,13,36.0,male,9,2014-02-16,760.500000,760.500000,NO,...,9.000000,9,0.000000,0,4.000000,4,2.000000,2,36.000000,36
9986,fASOcuHw3iIELGCkOAU++TefwO6XQpvEODHlhOBmy9k=,0,13,22.0,male,9,2011-08-11,141.550000,149.000000,NO,...,9.000000,9,0.000000,0,20.000000,20,1.000000,1,38.000000,38
9987,ihn5h97m1poSgOqCvG+68bERx5Nf2czIh2fXHBhL2q4=,1,12,28.0,male,9,2010-07-10,715.500000,715.500000,NO,...,9.000000,9,0.000000,0,4.000000,4,3.000000,3,32.000000,32
9988,jCT0eoUQ8MVUt9R0YVrM/fXPpRSrXd+pzXpO7AaYX10=,0,15,21.0,male,9,2015-10-23,223.500000,223.500000,NO,...,9.000000,9,0.000000,0,10.000000,10,1.000000,1,38.000000,38
9989,eexSSjCLRlmIRUIFL4JZZC//rcDt9ByRQ06Bu+OIhRc=,0,13,20.0,male,9,2011-09-06,137.538462,143.269231,NO,...,9.000000,9,0.000000,0,26.000000,26,2.000000,2,38.000000,38
9990,UwZOsxyIpUUrm1QTwjjlaPfZEPQ/A8bhqayL29qyCKs=,0,10,30.0,male,9,2004-07-18,184.058824,192.823529,NO,...,9.000000,9,0.000000,0,17.000000,17,1.000000,1,38.000000,38
9991,G3vP0QKBPe1wDIpX1s0QbnZ+Im59Pda3kIq8RRcK2wY=,0,1,42.0,male,4,2016-03-05,195.857143,195.857143,NO,...,4.000000,4,0.000000,0,7.000000,7,1.000000,1,38.000000,38
9992,6Ep/ii2c0PJCjHry+x/ZOPhOagkhDbrY/VdfDvSkpy4=,0,12,28.0,male,9,2007-11-03,156.555556,156.555556,NO,...,9.000000,9,0.000000,0,9.000000,9,3.000000,3,29.000000,29
9993,81mWxEEgssUK8g9A8kliUeXE7qddZBWXbjWzEXQyJm8=,0,13,20.0,male,9,2008-10-02,142.521739,149.000000,NO,...,9.000000,9,0.000000,0,23.000000,23,1.000000,1,38.000000,38
9994,be/PX+Ym3N5bWMRpXqRhcUVpElhIfgMHddJ3ry2IChw=,1,4,28.0,male,9,2007-11-14,1788.000000,1788.000000,NO,...,9.000000,9,0.000000,0,1.000000,1,1.000000,1,38.000000,38
9995,KjqfSHmF+J8nc0EA2PH/PKYuJAp9e5oD+1myD8BLTXo=,0,4,103.0,male,4,2016-04-26,149.000000,149.000000,NO,...,4.000000,4,0.000000,0,10.000000,10,1.000000,1,38.000000,38
9996,8ou+6o6cP0nPYD6eSmTS+0OwJ+HqhV3q7DupZ5Q1b5Y=,0,4,24.0,male,3,2014-12-06,870.250000,870.250000,NO,...,3.000000,3,0.000000,0,4.000000,4,2.000000,2,38.000000,38
9997,TVT4UlIbIJ+hKKyoLwGxzqbnpSFCtw0yJ+yFKzBn14I=,0,6,20.0,male,3,2012-11-23,0.000000,0.000000,NO,...,3.000000,3,0.000000,0,1.000000,1,1.000000,1,17.000000,17
9998,cWG9y1tDtAZNJpail7XIdraMdmw3mQ6TO/ml9XDWSG4=,0,4,32.0,male,9,2008-06-25,156.000000,156.000000,NO,...,9.000000,9,0.000000,0,15.000000,15,2.000000,2,36.000000,36
9999,JuDXxSTn0DzriXseYu+to2ereZJB2WVBXwGVAYeQvmw=,0,21,25.0,male,4,2016-01-06,235.222222,235.222222,NO,...,4.000000,4,0.000000,0,9.000000,9,2.000000,2,38.000000,38

In [14]:
XP.iloc[:,ncols:].astype(float)

,GroupBy_GENDER_mean_of_PLAN_LIST_PRICE,GroupBy_GENDER_max_of_PLAN_LIST_PRICE,GroupBy_GENDER_mean_of_AVG_AMOUNT_PAID,GroupBy_GENDER_max_of_AVG_AMOUNT_PAID,GroupBy_GENDER_mean_of_CITY,GroupBy_GENDER_max_of_CITY,GroupBy_GENDER_mean_of_AGE,GroupBy_GENDER_max_of_AGE,GroupBy_GENDER_mean_of_REGISTRATION_METHOD,GroupBy_GENDER_max_of_REGISTRATION_METHOD,...,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_REGISTRATION_METHOD,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_REGISTRATION_METHOD,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_TIMES_UNDER_PAID,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_TIMES_UNDER_PAID,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_TRANSACTIONS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_TRANSACTIONS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_NUM_PAYMENT_METHODS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_NUM_PAYMENT_METHODS,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_mean_of_COMMON_PAYMENT_METHOD,GroupBy_GENDER_REGISTRATION_DATE_AUTO_RENEW_max_of_COMMON_PAYMENT_METHOD
0,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,3.000000,3.0,0.000000,0.0,27.000000,27.0,2.000000,2.0,37.000000,37.0
1,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,8.000000,9.0,0.000000,0.0,24.500000,26.0,2.000000,3.0,39.500000,41.0
2,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,8.000000,9.0,0.000000,0.0,24.500000,26.0,2.000000,3.0,39.500000,41.0
3,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,7.000000,7.0,0.000000,0.0,19.000000,19.0,1.000000,1.0,39.000000,39.0
4,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,7.000000,9.0,0.750000,2.0,25.250000,27.0,1.250000,2.0,40.250000,41.0
5,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,7.000000,9.0,0.750000,2.0,25.250000,27.0,1.250000,2.0,40.250000,41.0
6,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,7.000000,9.0,0.750000,2.0,25.250000,27.0,1.250000,2.0,40.250000,41.0
7,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,7.000000,9.0,0.750000,2.0,25.250000,27.0,1.250000,2.0,40.250000,41.0
8,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,8.333333,9.0,0.333333,1.0,26.333333,29.0,1.666667,2.0,36.666667,40.0
9,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,8.333333,9.0,0.333333,1.0,26.333333,29.0,1.666667,2.0,36.666667,40.0
10,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,8.333333,9.0,0.333333,1.0,26.333333,29.0,1.666667,2.0,36.666667,40.0
11,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,7.000000,7.0,0.000000,0.0,15.000000,15.0,1.000000,1.0,41.000000,41.0
12,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,4.000000,4.0,0.000000,0.0,8.000000,8.0,1.000000,1.0,39.000000,39.0
13,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,7.000000,7.0,1.000000,2.0,14.500000,15.0,1.500000,2.0,38.500000,41.0
14,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,7.000000,7.0,1.000000,2.0,14.500000,15.0,1.500000,2.0,38.500000,41.0
15,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,4.600000,7.0,0.000000,0.0,21.200000,26.0,1.400000,2.0,36.800000,41.0
16,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,4.600000,7.0,0.000000,0.0,21.200000,26.0,1.400000,2.0,36.800000,41.0
17,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,4.600000,7.0,0.000000,0.0,21.200000,26.0,1.400000,2.0,36.800000,41.0
18,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,4.600000,7.0,0.000000,0.0,21.200000,26.0,1.400000,2.0,36.800000,41.0
19,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,4.600000,7.0,0.000000,0.0,21.200000,26.0,1.400000,2.0,36.800000,41.0
20,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,1.000000,1.0,14.000000,14.0,3.000000,3.0,40.000000,40.0
21,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,6.000000,7.0,1.250000,5.0,21.000000,28.0,1.000000,1.0,40.750000,41.0
22,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,6.000000,7.0,1.250000,5.0,21.000000,28.0,1.000000,1.0,40.750000,41.0
23,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,6.000000,7.0,1.250000,5.0,21.000000,28.0,1.000000,1.0,40.750000,41.0
24,124.857767,1788.0,124.945897,1788.0,1.950427,22.0,27.483333,59.0,6.891774,13.0,...,6.000000,7.0,1.250000,5.0,21.000000,28.0,1.000000,1.0,40.750000,41.0
25,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,6.000000,9.0,0.000000,0.0,22.500000,26.0,1.000000,1.0,39.500000,40.0
26,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,6.000000,9.0,0.000000,0.0,22.500000,26.0,1.000000,1.0,39.500000,40.0
27,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,5.000000,7.0,0.000000,0.0,23.000000,27.0,1.000000,1.0,40.000000,41.0
28,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,5.000000,7.0,0.000000,0.0,23.000000,27.0,1.000000,1.0,40.000000,41.0
29,177.346092,1788.0,183.177443,1788.0,10.655596,22.0,29.750236,69.0,6.996360,13.0,...,8.333333,9.0,0.333333,1.0,8.333333,9.0,1.333333,2.0,40.333333,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,4.000000,4.0,2.000000,2.0,36.000000,36.0
9971,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,3.000000,3.0,3.000000,3.0,20.000000,20.0
9972,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,5.000000,5.0,1.000000,1.0,29.000000,29.0
9973,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,3.000000,3.0,1.000000,1.0,32.000000,32.0
9974,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,2.000000,2.0,1.000000,1.0,36.000000,36.0
9975,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,18.000000,18.0,1.000000,1.0,38.000000,38.0
9976,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,3.000000,3.0,1.000000,1.0,3.000000,3.0
9977,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,18.000000,18.0,1.000000,1.0,38.000000,38.0
9978,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,5.000000,5.0,2.000000,2.0,29.000000,29.0
9979,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,14.000000,14.0,1.000000,1.0,38.000000,38.0
9980,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,1.000000,1.0,1.000000,1.0,32.000000,32.0
9981,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,20.000000,20.0,2.000000,2.0,36.000000,36.0
9982,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,21.000000,21.0,1.000000,1.0,38.000000,38.0
9983,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,3.000000,3.0,1.000000,1.0,22.000000,22.0
9984,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,14.000000,14.0,2.000000,2.0,36.000000,36.0
9985,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,4.000000,4.0,2.000000,2.0,36.000000,36.0
9986,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,20.000000,20.0,1.000000,1.0,38.000000,38.0
9987,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,4.000000,4.0,3.000000,3.0,32.000000,32.0
9988,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,10.000000,10.0,1.000000,1.0,38.000000,38.0
9989,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,26.000000,26.0,2.000000,2.0,38.000000,38.0
9990,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,17.000000,17.0,1.000000,1.0,38.000000,38.0
9991,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,4.000000,4.0,0.000000,0.0,7.000000,7.0,1.000000,1.0,38.000000,38.0
9992,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,9.000000,9.0,3.000000,3.0,29.000000,29.0
9993,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,23.000000,23.0,1.000000,1.0,38.000000,38.0
9994,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,1.000000,1.0,1.000000,1.0,38.000000,38.0
9995,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,4.000000,4.0,0.000000,0.0,10.000000,10.0,1.000000,1.0,38.000000,38.0
9996,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,4.000000,4.0,2.000000,2.0,38.000000,38.0
9997,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,3.000000,3.0,0.000000,0.0,1.000000,1.0,1.000000,1.0,17.000000,17.0
9998,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,9.000000,9.0,0.000000,0.0,15.000000,15.0,2.000000,2.0,36.000000,36.0
9999,176.840934,1788.0,185.042635,1788.0,10.723312,22.0,30.085843,1030.0,6.827015,13.0,...,4.000000,4.0,0.000000,0.0,9.000000,9.0,2.000000,2.0,38.000000,38.0

In [15]:
XP.to_csv("churn_test_big_cols.csv.zip",compression='infer')